# Generated by Django 4.2.6 on 2023-10-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='auction_winner',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
